# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Scores")

model_instance <- Scores$new()

test_that("regression", {
  # tests for the property `regression` (RegressionScores)

  # uncomment below to test the property
  #expect_equal(model.instance$`regression`, "EXPECTED_RESULT")
})

test_that("binaryClassification", {
  # tests for the property `binaryClassification` (BinaryClassificationScores)

  # uncomment below to test the property
  #expect_equal(model.instance$`binaryClassification`, "EXPECTED_RESULT")
})

test_that("multiclassClassification", {
  # tests for the property `multiclassClassification` (MulticlassClassificationScores)

  # uncomment below to test the property
  #expect_equal(model.instance$`multiclassClassification`, "EXPECTED_RESULT")
})
