# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ModelScores")

model_instance <- ModelScores$new()

test_that("train", {
  # tests for the property `train` (array[Scores])

  # uncomment below to test the property
  #expect_equal(model.instance$`train`, "EXPECTED_RESULT")
})

test_that("test", {
  # tests for the property `test` (array[Scores])

  # uncomment below to test the property
  #expect_equal(model.instance$`test`, "EXPECTED_RESULT")
})

test_that("crossValidation", {
  # tests for the property `crossValidation` (array[Scores])

  # uncomment below to test the property
  #expect_equal(model.instance$`crossValidation`, "EXPECTED_RESULT")
})
