# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BinaryClassificationScores")

model_instance <- BinaryClassificationScores$new()

test_that("labels", {
  # tests for the property `labels` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`labels`, "EXPECTED_RESULT")
})

test_that("yName", {
  # tests for the property `yName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`yName`, "EXPECTED_RESULT")
})

test_that("folds", {
  # tests for the property `folds` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`folds`, "EXPECTED_RESULT")
})

test_that("accuracy", {
  # tests for the property `accuracy` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`accuracy`, "EXPECTED_RESULT")
})

test_that("balancedAccuracy", {
  # tests for the property `balancedAccuracy` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`balancedAccuracy`, "EXPECTED_RESULT")
})

test_that("precision", {
  # tests for the property `precision` (array[numeric])

  # uncomment below to test the property
  #expect_equal(model.instance$`precision`, "EXPECTED_RESULT")
})

test_that("recall", {
  # tests for the property `recall` (array[numeric])

  # uncomment below to test the property
  #expect_equal(model.instance$`recall`, "EXPECTED_RESULT")
})

test_that("f1Score", {
  # tests for the property `f1Score` (array[numeric])

  # uncomment below to test the property
  #expect_equal(model.instance$`f1Score`, "EXPECTED_RESULT")
})

test_that("jaccard", {
  # tests for the property `jaccard` (array[numeric])

  # uncomment below to test the property
  #expect_equal(model.instance$`jaccard`, "EXPECTED_RESULT")
})

test_that("matthewsCorrCoef", {
  # tests for the property `matthewsCorrCoef` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`matthewsCorrCoef`, "EXPECTED_RESULT")
})

test_that("confusionMatrix", {
  # tests for the property `confusionMatrix` (array[array[numeric]])

  # uncomment below to test the property
  #expect_equal(model.instance$`confusionMatrix`, "EXPECTED_RESULT")
})
