# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Doa")

model_instance <- Doa$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("method", {
  # tests for the property `method` (DoaMethod)

  # uncomment below to test the property
  #expect_equal(model.instance$`method`, "EXPECTED_RESULT")
})

test_that("data", {
  # tests for the property `data` (map(AnyType))

  # uncomment below to test the property
  #expect_equal(model.instance$`data`, "EXPECTED_RESULT")
})

test_that("createdAt", {
  # tests for the property `createdAt` (character)
  # The date and time when the feature was created.

  # uncomment below to test the property
  #expect_equal(model.instance$`createdAt`, "EXPECTED_RESULT")
})

test_that("updatedAt", {
  # tests for the property `updatedAt` (character)
  # The date and time when the feature was last updated.

  # uncomment below to test the property
  #expect_equal(model.instance$`updatedAt`, "EXPECTED_RESULT")
})
