# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RegressionScores")

model_instance <- RegressionScores$new()

test_that("yName", {
  # tests for the property `yName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`yName`, "EXPECTED_RESULT")
})

test_that("folds", {
  # tests for the property `folds` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`folds`, "EXPECTED_RESULT")
})

test_that("r2", {
  # tests for the property `r2` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`r2`, "EXPECTED_RESULT")
})

test_that("mae", {
  # tests for the property `mae` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`mae`, "EXPECTED_RESULT")
})

test_that("rmse", {
  # tests for the property `rmse` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`rmse`, "EXPECTED_RESULT")
})
