# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BoundingBoxDoa")

model_instance <- BoundingBoxDoa$new()

test_that("boundingBox", {
  # tests for the property `boundingBox` (array[array[numeric]])

  # uncomment below to test the property
  #expect_equal(model.instance$`boundingBox`, "EXPECTED_RESULT")
})
