# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MeanVarDoa")

model_instance <- MeanVarDoa$new()

test_that("bounds", {
  # tests for the property `bounds` (array[array[numeric]])

  # uncomment below to test the property
  #expect_equal(model.instance$`bounds`, "EXPECTED_RESULT")
})
