# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test LeverageDoa")

model_instance <- LeverageDoa$new()

test_that("hStar", {
  # tests for the property `hStar` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`hStar`, "EXPECTED_RESULT")
})

test_that("doaMatrix", {
  # tests for the property `doaMatrix` (array[array[numeric]])

  # uncomment below to test the property
  #expect_equal(model.instance$`doaMatrix`, "EXPECTED_RESULT")
})
