# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RPbpkConfig")

model_instance <- RPbpkConfig$new()

test_that("odeSolver", {
  # tests for the property `odeSolver` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`odeSolver`, "EXPECTED_RESULT")
})
